import type { Artist, ReviewItem } from "@vendorapp/shared";

export const PUBLIC_FALLBACK_ARTISTS: Artist[] = [
  {
    slug: "ava-maseko",
    name: "Ava Maseko",
    role: "Wedding Photographer",
    location: "Cape Town",
    rating: "4.9",
    averageRating: 4.9,
    totalReviews: 42,
    hourlyRate: 2800,
    isAvailable: true,
    isVerified: true,
    profileViews: 284,
    tags: ["weddings", "editorial", "luxury"],
    services: ["Full-day wedding coverage", "Engagement sessions", "Editorial portraits"],
    specialties: ["Weddings", "Editorial"],
    category: { id: "photography", name: "Photographers", slug: "photography" },
    pricingSummary: "From R2,800 for signature coverage.",
    availabilitySummary: "Available this month across the Western Cape.",
    portfolioImages: [
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=900&q=80",
    ],
    bio: "Editorial wedding storytelling with a refined, documentary point of view.",
  },
  {
    slug: "kai-dlamini",
    name: "Kai Dlamini",
    role: "Videographer",
    location: "Johannesburg",
    rating: "4.8",
    averageRating: 4.8,
    totalReviews: 31,
    hourlyRate: 3200,
    isAvailable: true,
    isVerified: true,
    profileViews: 231,
    tags: ["brand", "events", "campaigns"],
    services: ["Brand films", "Campaign edits", "Event recaps"],
    specialties: ["Brand Campaigns", "Corporate Events"],
    category: { id: "videography", name: "Videographers", slug: "videography" },
    pricingSummary: "From R3,200 for premium event films.",
    availabilitySummary: "Fast turnaround for branded work and events.",
    portfolioImages: [
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
    ],
    bio: "Cinematic motion work for launches, campaigns, and high-energy events.",
  },
  {
    slug: "nuri-studio",
    name: "Nuri Studio",
    role: "Content Creator",
    location: "Pretoria",
    rating: "4.8",
    averageRating: 4.8,
    totalReviews: 24,
    hourlyRate: 2200,
    isAvailable: true,
    isVerified: true,
    profileViews: 198,
    tags: ["content", "brand", "social"],
    services: ["Reels production", "Campaign content", "Lifestyle shoots"],
    specialties: ["Brand Campaigns", "Lifestyle"],
    category: { id: "content", name: "Content creators", slug: "content" },
    pricingSummary: "From R2,200 for social-first content sets.",
    availabilitySummary: "Open for weekly retainers and campaign bursts.",
    portfolioImages: [
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=900&q=80",
    ],
    bio: "Fast-moving social content with clean styling and conversion-aware storytelling.",
  },
  {
    slug: "gearline-collective",
    name: "Gearline Collective",
    role: "Automotive Specialist",
    location: "Durban",
    rating: "4.7",
    averageRating: 4.7,
    totalReviews: 18,
    hourlyRate: 3000,
    isAvailable: false,
    isVerified: true,
    profileViews: 162,
    tags: ["automotive", "commercial", "motion"],
    services: ["Showroom campaigns", "Track-day coverage", "Commercial stills"],
    specialties: ["Commercial", "Automotive"],
    category: { id: "automotive", name: "Automotive specialists", slug: "automotive" },
    pricingSummary: "From R3,000 for showroom and track-day coverage.",
    availabilitySummary: "Limited slots, ideal for launches and rolling campaigns.",
    portfolioImages: [
      "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
    ],
    bio: "Sharper automotive storytelling for launches, dealer campaigns, and motion-led content.",
  },
  {
    slug: "mahala-design",
    name: "Mahala Design",
    role: "Designer",
    location: "Cape Town",
    rating: "4.9",
    averageRating: 4.9,
    totalReviews: 27,
    hourlyRate: 2500,
    isAvailable: true,
    isVerified: true,
    profileViews: 205,
    tags: ["design", "branding", "editorial"],
    services: ["Identity systems", "Campaign art direction", "Brand refreshes"],
    specialties: ["Brand Campaigns", "Commercial"],
    category: { id: "design", name: "Designers", slug: "design" },
    pricingSummary: "From R2,500 for identity and campaign systems.",
    availabilitySummary: "Available for design retainers and launch packages.",
    portfolioImages: [
      "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
    ],
    bio: "Elegant brand systems and launch visuals with editorial restraint.",
  },
  {
    slug: "sunday-frame",
    name: "Sunday Frame",
    role: "Event Creator",
    location: "Johannesburg",
    rating: "4.8",
    averageRating: 4.8,
    totalReviews: 36,
    hourlyRate: 2600,
    isAvailable: true,
    isVerified: false,
    profileViews: 187,
    tags: ["events", "content", "live"],
    services: ["Event coverage", "Recap edits", "Social-ready live content"],
    specialties: ["Corporate Events", "Music"],
    category: { id: "events", name: "Event creators", slug: "events" },
    pricingSummary: "From R2,600 for event coverage and content packs.",
    availabilitySummary: "Weekend and after-hours production slots available.",
    portfolioImages: [
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80",
    ],
    bio: "Live event capture designed for momentum, recap value, and social-ready delivery.",
  },
];

export function findPublicFallbackArtist(slug: string): Artist | undefined {
  return PUBLIC_FALLBACK_ARTISTS.find((artist) => artist.slug === slug);
}

export function getPublicFallbackReviews(artist: Artist): ReviewItem[] {
  const rating =
    typeof artist.averageRating === "number"
      ? artist.averageRating
      : Number.parseFloat(artist.rating || "4.8");
  const roundedRating = Number.isFinite(rating) ? Number(rating.toFixed(1)) : 4.8;
  const primarySpecialty =
    artist.specialties?.[0] ?? artist.services?.[0] ?? artist.category?.name ?? artist.role;

  return [
    {
      id: `${artist.slug}-preview-review-1`,
      bookingId: `${artist.slug}-preview-booking-1`,
      rating: roundedRating,
      comment: `${artist.name.split(" ")[0]} was easy to work with, communicative throughout, and delivered polished ${primarySpecialty.toLowerCase()} work on schedule.`,
      isPublic: true,
      createdAt: "2026-03-15T09:00:00.000Z",
      updatedAt: "2026-03-15T09:00:00.000Z",
      bookingTitle: `${primarySpecialty} booking`,
      eventDate: "2026-03-08T09:00:00.000Z",
      reviewer: {
        id: `${artist.slug}-reviewer-1`,
        name: "Preview Client",
      },
      artist: {
        id: artist.id ?? `${artist.slug}-artist`,
        name: artist.name,
        slug: artist.slug,
      },
    },
    {
      id: `${artist.slug}-preview-review-2`,
      bookingId: `${artist.slug}-preview-booking-2`,
      rating: Math.max(4.5, roundedRating - 0.1),
      comment: `Strong creative direction, fast responses, and a clear handover process. The profile matched the final delivery well.`,
      isPublic: true,
      createdAt: "2026-02-20T11:30:00.000Z",
      updatedAt: "2026-02-20T11:30:00.000Z",
      bookingTitle: `Repeat ${primarySpecialty.toLowerCase()} project`,
      eventDate: "2026-02-14T11:30:00.000Z",
      reviewer: {
        id: `${artist.slug}-reviewer-2`,
        name: "Marketplace Preview",
      },
      artist: {
        id: artist.id ?? `${artist.slug}-artist`,
        name: artist.name,
        slug: artist.slug,
      },
    },
  ];
}
